pipeline {

    agent any



    stages {

        stage('Build') {

            steps {

                echo 'Building..'

                npm install

                sh 'npm run build'

            }

        }

        stage('Test') {

            steps {

                echo 'Testing..'

                sh 'npm run test:e2e'

            }

        }

        stage('Deploy') {

            steps {

                echo 'Deploying....'

                serve -s dist

            }

        }

    }

}